title: Amaranth Acres Worker Logger
description: >- # this means to ignore newlines until "baseurl:"
  Hours logger app for Amaranth Acres workers.
github_username:  sardination

# Build settings
theme: minima